blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ Question or Discussion"
    url: https://github.com/antropos17/Aegis/issues
    about: "For general questions, open a blank issue with the 'question' label"
